version: '3'

services:
  database:
    # Official Postgres image from DockerHub (use the last version)
    image: 'postgres:latest'
    ports:
      - 5433:5432

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin123
      POSTGRES_DB: db_black_creek